RG-8892 - Implementação de endpoint para exclusão de apostas
chavesef/dape-api pull request #10
Opened 2024-11-06 18:23 UTC by chavesef

2024-11-18 17:04 UTC, lekramon submitted a review, later dismissed

2024-11-18 18:26 UTC, uttoniWork requested changes

2024-11-18 18:26 UTC, uttoniWork commented on src/test/java/com/dape/api/cucumber/BetDeletionSteps.java
> +        System.out.println(deleteResponse.body());
Remover prints

2024-11-18 18:26 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +        InvalidConditionException invalidConditionException =
final, vale para as demais instâncias nos outros testes

2024-11-18 18:26 UTC, uttoniWork commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +        Bet betToDelete = getBetById(idtBet);
final

2024-11-18 18:26 UTC, uttoniWork commented on src/main/java/com/dape/api/domain/exception/InvalidConditionException.java
Nome muito vago para uma excessão, para o contexto em questão recomendaria algo como InvalidStatusException

2024-11-19 13:27 UTC, lekramon approved these changes

2024-11-21 15:39 UTC, merged