RG-8483 Configuração do Flyway para migração criando e populando tabelas
chavesef/dape-api pull request #2
Opened 2024-08-01 14:38 UTC by chavesef

2024-08-01 19:26 UTC, uttoniWork requested changes

2024-08-01 19:26 UTC, uttoniWork commented on README.md
> +A API REST realiza as operações CRUD(Create, Retrieve, Update e Delete) no banco de dados Oracle
Errado não tá porque a api vai fazer, mas ela não faz isso ainda

2024-08-01 19:26 UTC, uttoniWork commented on README.md
Adicionar trecho sobre o flyway, explicando para o que está sendo usado e linkando onde estão os arquivos de migração

2024-08-01 19:26 UTC, uttoniWork commented on src/main/resources/db/migration/V1.1__CREATING_TABLES_RG_8483.sql
> +    DAT_UPDATED TIMESTAMP,
DAT_UPDATED not null também para todas as tabelas que tiverem

2024-08-01 19:26 UTC, uttoniWork commented on src/main/resources/db/migration/V1.2__INSERTING_DATA_RG_8483.sql
> +INSERT INTO BET (NUM_ODD, FLG_SELECTED, DAT_CREATED, DAT_UPDATED, DES_BET, COD_BET_STATUS)
Temos um endpoint mapeado pra criar apostas, não precisa inserir tantas via migration, acho que pode remover

2024-08-01 19:59 UTC, lekramon commented on README.md
criar sumário

2024-08-01 20:03 UTC, lekramon commented
para os próximos PR's colocar uma sucinta descrição na branch, como por exemplo: "feature/RG-8483-configura-flyway"

2024-08-01 20:30 UTC, lekramon commented on src/main/resources/db/migration/V1.2__INSERTING_DATA_RG_8483.sql
> +COMMIT;
remover esse COMMIT

2024-08-02 18:39 UTC, lekramon approved these changes

2024-08-02 21:06 UTC, uttoniWork approved these changes

2024-08-05 13:34 UTC, merged