RG-8484 - Criação de contrato dos endpoints
chavesef/dape-api pull request #3
Opened 2024-08-06 19:55 UTC by chavesef

2024-08-08 17:47 UTC, lekramon commented on src/main/resources/dape-api-contract.yml
> +        - dat_created
A data de criação e a data de atualização, não precisam ser passadas na requisição de criação

2024-08-08 17:48 UTC, lekramon commented on src/main/resources/dape-api-contract.yml
> +    BetCreateResponse:
Você pode adicionar as datas no response de criação do objeto

2024-08-09 14:23 UTC, lekramon commented on src/main/resources/dape-api-contract.yml
> +        cod_bet_status:
Para melhorar a compreensão de quem está consultando o endpoint, seria ideal que cod_bet_status retornasse a string correspondente ao status em vez de apenas o código. A aplicação pode fazer o mapeamento do código para a string descritiva, facilitando o entendimento e uso do retorno

2024-08-09 14:26 UTC, lekramon commented on src/main/resources/dape-api-contract.yml
> +    get:
Esse endpoint deve ser paginado

2024-08-09 14:29 UTC, lekramon commented
https://docs.spring.io/spring-data/rest/reference/paging-and-sorting.html
https://www.baeldung.com/rest-api-pagination-in-spring

2024-08-12 20:01 UTC, lekramon submitted a review, later dismissed

2024-08-12 20:14 UTC, thyagofr3s requested changes

2024-08-12 20:14 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +        - name: page
Seria interessante disponibilizar um query param limit tambem

2024-08-12 20:14 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +      responses:
Creio que tambem seja possivel ter um 400 em casos onde dados invalidos sao enviados atraves de algum query param

2024-08-12 20:14 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +  /bets/status/{idt_bet}:
Seguindo o REST, o correto(ou o mais proximo do correto), seria /bets/idt_bet/status

2024-08-12 20:14 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +        - name: ticket_type
Seria interessante lista os possiveis valores ENUM

2024-08-12 20:14 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +        - name: page
Mesma sugestao do outro, disponibilizar o quer param limit

2024-08-12 20:14 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +            example: "PENDING"
Analisar a possibilidade de usar ENUMs

2024-08-12 20:41 UTC, mrvasconcelos commented on src/main/resources/dape-api-contract.yml
> +  /bets:
Faz sentido o nome desse endpoint estar no plural? Tirando o caso do get, que retorna uma betList, as demais operações são unitárias.

2024-08-13 20:16 UTC, leandro-manoel approved these changes

2024-08-14 19:23 UTC, lekramon approved these changes

2024-08-15 16:53 UTC, mrvasconcelos approved these changes

2024-08-15 16:54 UTC, merged