RG-8497 - Criação de cenários de teste
chavesef/dape-api pull request #4
Opened 2024-08-19 15:40 UTC by chavesef

2024-08-20 14:02 UTC, lekramon reviewed
Faltou configurar a integração do Cucumber com o Spring Boot e a configuração do Cucumber Runner

2024-08-20 19:13 UTC, thyagofr3s requested changes

2024-08-20 19:13 UTC, thyagofr3s commented on src/main/resources/dape-api-contract.yml
> +          description: Not found, Cliente ou aposta não encontrados
Eu imagino que esse caso nao seja valido pois não há nenhum parametro no caminho do recurso q possa causar um 404. Se a aposta faz parte do corpo da requiscao o bad request atende o caso

2024-08-20 20:09 UTC, lekramon reviewed
Coloque Tags nos cenários, um para funcionalidade e um para cada cenário.

2024-08-22 13:25 UTC, thyagofr3s requested changes

2024-08-23 14:56 UTC, lekramon commented on src/test/resources/features/atualizacaoApostas.feature
> +  Cenario: Atualização de aposta com sucesso
Utilizar verbos no nome dos cenarios, como por exemplo: Cenário: Atualizar uma aposta existente com sucesso

2024-08-23 14:56 UTC, lekramon commented on src/test/resources/features/atualizacaoApostas.feature
> +    Entao o serviço de atualização deve retornar o status code 200
Então

2024-08-23 15:01 UTC, lekramon commented on src/test/resources/features/atualizacaoApostas.feature
> +    Quando uma requisição de atualização de aposta for realizada com odd 2.20 e descrição "Vitória do Vitória" e idt_bet 2024
Quando uma requisição de atualização de aposta for realizada com odd 2.20, descrição "Vitória do Vitória" e idt_bet 2024

2024-08-23 15:08 UTC, lekramon commented on src/test/resources/features/atualizacaoStatusApostas.feature
> +Funcionalidade: Realizar atualização do status de apostas disponíveis no banco de dados
adicionar um cenario para validar se você tentar alterar uma aposta que já está como RED para GREEN (Não deve permitir por exemplo), pense em uma maquina de estado. Inclusive faltou isso em sua arquitetura, seria bom ter para os fluxo que envolvem atualização de status.

2024-08-23 15:19 UTC, lekramon commented on src/test/resources/features/atualizacaoStatusApostas.feature
> +    Entao o serviço de atualização deve retornar o status code 200
Tome cuidado com o reuso de steps, esse step está nos arquivos: "atualizacaoApostas.feature, atualizacaoStatusApostas.feature"

Nesse caso acredito que não haverá problema, pois o comportamento esperado e o objeto provavelmente será o mesmo. Mas tome ponto:

O comportamento esperado for diferente: Se você tiver o mesmo step, mas espera um comportamento diferente em diferentes cenários ou features, então, nesse caso, você precisaria diferenciar os steps.

Confusão na Manutenção: Se os steps são idênticos, mas em diferentes contextos ou funcionalidades, pode ser difícil, em termos de manutenção, identificar rapidamente qual step está sendo executado e qual lógica ele deve seguir. Nesse caso, seria útil tornar os steps mais específicos.

2024-08-23 15:24 UTC, lekramon commented on src/test/resources/features/atualizacaoApostas.feature
> +    Entao o serviço de atualização deve retornar o status code 200
200 - "OK"

2024-08-23 15:24 UTC, lekramon commented on src/test/resources/features/atualizacaoStatusApostas.feature
> +    Entao o serviço de cadastro deve retornar o status code 400
400 - "Bad Request"

2024-08-23 15:25 UTC, lekramon commented on src/test/resources/features/atualizacaoStatusApostas.feature
> +    Entao o serviço de cadastro deve retornar o status code 404
404 - "Not Found"

2024-08-23 15:25 UTC, lekramon commented on src/test/resources/features/atualizacaoStatusApostas.feature
> +    Então o serviço de atualização deve retornar o status code 500
500 - "Internal Server Error"

2024-08-23 15:26 UTC, lekramon commented
O que eu comentei vale para todos os cenários, análise eles e coloque as novas solicitações, entendo que vale a pena a criação da maquina de estado na arquitetura.

2024-08-23 19:59 UTC, Droissor commented on src/test/resources/features/cadastroApostas.feature
> +    Entao o serviço de cadastro deve retornar o status code 400
esses cenarios de erro onde se tenta realizar uma alteracao nos dados de base cadastral é importante validar que não houveram alterações e a base / registro se mantem no mesmo estado

2024-08-23 19:59 UTC, Droissor commented on src/test/resources/features/cadastroBilhetes.feature
> +    E o seguinte bilhete deve ser cadastrado no banco de dados
Como conseguimos validar o vinculo de um bilhete cadastrado com as apostas registradas, ainda mais numm cenario de multiplas?

2024-08-23 19:59 UTC, Droissor commented on src/test/resources/features/remocaoApostas.feature
> +  Cenário: Remoção de uma aposta com serviço indisponível
Eu posso deletar uma aposta com flg_selected = 1? Vale um cenario para isso

2024-08-23 19:59 UTC, Droissor commented on src/test/resources/features/atualizacaoApostas.feature
> +      | 1       | 2.13    | 0            | 2024-08-15  | 2024-08-15  | Vitória do São Paulo        | PENDING    |
Eu posso atualizar uma aposta com flg_selected = 1? Vale um cenario para isso

2024-08-26 13:53 UTC, Droissor approved these changes

2024-08-26 18:24 UTC, lekramon approved these changes

2024-08-26 19:58 UTC, mrvasconcelos commented on src/test/resources/features/cadastroApostas.feature
> +Funcionalidade: Realizar o cadastro de novas apostas no banco de dados
Existe a possibilidade de cadastrar uma aposta com a mesma descrição de outra aposta já existente? Vale um cenário para isso?

2024-08-26 20:37 UTC, lekramon approved these changes

2024-08-27 20:06 UTC, mrvasconcelos approved these changes

2024-08-28 14:10 UTC, Droissor approved these changes

2024-08-28 14:12 UTC, merged