RG-8594 - Criação de endpoint de atualização de apostas
chavesef/dape-api pull request #7
Opened 2024-09-24 14:08 UTC by chavesef

2024-09-25 13:29 UTC, uttoniWork requested changes

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/adapter/controller/DapeExceptionHandlerTest.java
> +        final BetNotExistentException exception = Mockito.mock(BetNotExistentException.class);
Evitar passar mock como parametro direto para o método sendo testado, instancie a exceção. O método getMessage dessa exception provavelmente está retornando null, por isso não falha no assert

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/adapter/controller/stub/BetRequestStub.java
Criar os stubs como builders, assim podemos ter um método padrão que cria com valores fixos para todos os campos, mas teremos também métodos que alterem cada campo de acordo com a necessidade. Evita a necessidade de criar diversos métodos para cada objeto específico que for necessário e evidencia os campos diferentes nos testes.

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/cucumber/BetUpdateSteps.java
> +        if(servicoIndisponivel)
Abstrair lógica dos ifs para um método privado que recebe a response da chamada e retorna a response entity criada

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/cucumber/BetRegistrationSteps.java
> +                cadastroResponseEntity = ResponseEntity.status(post.statusCode()).body(post.getBody().as(BetResponse.class));
Abstrair lógica dos ifs para um método privado que recebe a response da chamada e retorna a response entity criada

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/cucumber/BetUpdateSteps.java
> +        Bet expectedBet = updatedBets.get(0);
Adicionar final, verificar demais instâncias

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +        assertEquals(expectedBet.getDesBet(), actualBet.getDesBet());
Utilizar um único assert para validar o objeto todo

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +    void updatedBetInexistent(){
Renomear método, dá a entender que é possível atualizar uma bet inexistente

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +    void updatedBetSelected(){
Renomear método, dá a entender que é possível atualizar uma bet selected

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +    void updatedBetResolved(){
Renomear método, dá a entender que é possível atualizar uma bet resolved

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +        assertThrows(BetNotExistentException.class, () -> betService.updateBet(idtBet, betRequest));
Pegar excessão retornada pelo fluxo e validar mensagem, vale para os demais casos

2024-09-25 13:29 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +        final Long idtBet = 1L;
Fique atento ao momento em que intancia os objetos, é uma boa prática criá-los logo antes do uso principalmente para evitar a confusão futura na manutenção do código e a possibilidade de serem usados indevidamente em outros fluxos. Revisar demais testes

2024-09-26 17:20 UTC, uttoniWork commented on src/main/java/com/dape/api/adapter/controller/DapeExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleBadRequestExceptions(Exception e){
Renomear método, ele n trata um bad request, mas sim excessões que geram esse status de retorno. Poderia ser algo como handleInvalidRequestDataExceptions

2024-09-26 17:27 UTC, uttoniWork requested changes

2024-09-26 18:05 UTC, uttoniWork submitted a review, later dismissed

2024-09-30 14:09 UTC, lekramon commented on src/main/java/com/dape/api/adapter/controller/BetOperationsController.java
> +        LOGGER.info("Método POST chamado para cadastrar uma nova aposta com descrição={} e odd={}", betRequest.getDesBet(), betRequest.getNumOdd());
não é uma regra, mas normalmente utilizamos um padrão nos loggers, que seria "m=nomeDoMetodo, msg= blablabla"

2024-09-30 14:10 UTC, lekramon commented on src/main/java/com/dape/api/adapter/dto/response/BetResponse.java
> +    public BetResponse(Long idtBet, String desBet, BigDecimal numOdd,
esse construtor não está sendo usado

2024-09-30 15:15 UTC, lekramon reviewed
os seus testes integrados não estão rodando na suite de testes, verificar o motivo

2024-10-01 19:01 UTC, lekramon approved these changes

2024-10-01 20:04 UTC, uttoniWork approved these changes

2024-10-03 21:47 UTC, mrvasconcelos commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +        return betToUpdate.getFlgSelected() == 1 || betToUpdate.getBetStatusEnum() != BetStatusEnum.PENDING;
O que significa flgSelected == 1? Poderia utilizar uma constante para melhor legibilidade

2024-10-03 21:51 UTC, mrvasconcelos commented on src/test/java/com/dape/api/cucumber/BetRegistrationSteps.java
> +        if(servicoIndisponivel)
Inglês para manter no padrão

2024-10-03 21:52 UTC, mrvasconcelos commented on src/test/java/com/dape/api/cucumber/BetUpdateSteps.java
> +    private boolean servicoIndisponivel;
Inglês também

2024-10-07 13:41 UTC, mrvasconcelos approved these changes

2024-10-07 13:44 UTC, uttoniWork approved these changes

2024-10-07 14:01 UTC, lekramon approved these changes

2024-10-07 14:02 UTC, merged