RG-8595 - Criação de endpoint de atualização de status de apostas
chavesef/dape-api pull request #8
Opened 2024-10-08 15:01 UTC by chavesef

2024-10-09 17:59 UTC, lekramon commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +        Bet betToUpdate = getBetById(idtBet);
final

2024-10-09 17:59 UTC, lekramon commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +        if(betStatus.getBetStatus() == BetStatusEnum.GREEN || betStatus.getBetStatus() == BetStatusEnum.RED) {
utilize List ou Set adicionando o status validos para atualização, você pode criar como constante

2024-10-09 17:59 UTC, lekramon commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +    private void updateBetStatusField(Bet betToUpdate, BetStatusRequest betStatus) {
dá pra melhorar o nome desse metodo deixando claro quais são os campos que ele atualiza

2024-10-09 17:59 UTC, lekramon commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +        return betToUpdate.getBetStatusEnum() != BetStatusEnum.PENDING;
esse método é necessário? acho que você está utilizando a mesma lógica duas vezes

2024-10-09 17:59 UTC, lekramon commented on src/main/java/com/dape/api/usecase/service/BetService.java
estou achando essa classe muito confusa, verifique a utilização de padrões de projeto para melhora-la

2024-10-09 17:59 UTC, lekramon commented on src/test/java/com/dape/api/adapter/controller/BetOperationsControllerTest.java
> +    void updateBetStatus(){
Você consegue diminuir bastante esse seu teste, você está instanciando bastante coisas que não precisa, pode passar os valores diretamente, como por exemplo:

        when(betService.updateBetStatus(anyLong(), any(BetStatusRequest.class))).thenReturn(BetStub.builder().withBetStatusEnum(BetStatusEnum.GREEN).build());
        
 Se aplica aos demais.

2024-10-09 18:01 UTC, lekramon commented on src/test/java/com/dape/api/cucumber/BetStatusUpdateSteps.java
> +            if (patch.jsonPath().get("$") instanceof List)
``
    private ResponseEntity<Object> createResponseEntityFromRestAssuredResponse(Response response) {
        if (response.getStatusCode() == HttpStatus.(STATUS_ESPERADO).value()) {
            return new ResponseEntity<>(response.as(Response.class), HttpStatus.valueOf(response.getStatusCode()));
        }
        return new ResponseEntity<>(response, HttpStatus.valueOf(response.getStatusCode()));
    }
``

2024-10-09 18:06 UTC, uttoniWork requested changes

2024-10-09 18:06 UTC, uttoniWork commented on src/test/resources/features/betStatusUpdate.feature
> +    E o banco de dados de atualização de status não deve ser modificado
Step um pouco genérico demais, da a entender que vamos validar que nenhuma tabela do banco sofreu alteração. Poderia ser algo mais específico indicando o que espera ser encontrado na tabela apenas, algo como: E a tabela bet deve conter os seguintes dados ou  E a tabela bet deve conter os registros abaixo

2024-10-09 18:06 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
Adicionar testes para:

- Caso em que a bet não esteja com status PENDING e não possa ser alterada;
- Caso em que a bet não seja encontrada.

2024-10-09 18:06 UTC, uttoniWork commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +        LOGGER.info("m=updateBetStatus, msg=Atualizando status da aposta para: {}", betToUpdate.getBetStatusEnum());
Informar o ID da bet sendo atualizada, facilita identificar caso tenhamos problemas. Adicionar ID nas mensagens das excessões também

2024-10-09 19:46 UTC, chavesef commented on src/main/java/com/dape/api/adapter/controller/BetOperationsController.java
> +    @PatchMapping("bet/{idtBet}/status")
Depois quando eu for mapear o endpoint /ticket definido no contrato n vai ficar estranho?

2024-10-11 15:16 UTC, lekramon commented on src/test/java/com/dape/api/cucumber/BetRegistrationSteps.java
> +        Response postResponse = given().body(betRequest).contentType(ContentType.JSON).when()
final

2024-10-11 15:18 UTC, lekramon commented on src/test/java/com/dape/api/cucumber/BetStatusUpdateSteps.java
> +        Response patchResponse = RestAssured.given().body(betStatusRequest).contentType(ContentType.JSON)
final e utilize o import estático

2024-10-11 15:23 UTC, lekramon commented on src/test/java/com/dape/api/cucumber/BetRegistrationSteps.java
> +        if (postResponse.getStatusCode() == HttpStatus.OK.value()) {
HttpStatus.CREATED

2024-10-11 15:24 UTC, lekramon commented on src/test/java/com/dape/api/cucumber/BetUpdateSteps.java
> +        Response patchResponse = RestAssured.given().body(betRequest).contentType(ContentType.JSON)
final e utilize import estático

2024-10-11 17:23 UTC, lekramon submitted a review, later dismissed

2024-10-17 13:03 UTC, uttoniWork commented on src/main/java/com/dape/api/adapter/controller/BetOperationsController.java
> +    @PatchMapping("bet/{idtBet}/status")
Os endpoints com path /ticket deveriam ficar em outro controller

2024-10-17 14:20 UTC, lekramon approved these changes

2024-10-18 11:55 UTC, merged