RG-8596 - Criação de endpoint para consulta de apostas
chavesef/dape-api pull request #9
Opened 2024-10-24 14:11 UTC by chavesef

2024-10-28 19:04 UTC, leandro-manoel submitted a review, later dismissed

2024-10-28 19:48 UTC, uttoniWork requested changes

2024-10-28 19:48 UTC, uttoniWork commented on src/main/java/com/dape/api/usecase/service/BetService.java
> +    private Integer getCodBetStatus(String betStatus) {
A lógica de pegar o código do status e as excessões lançadas podem ficar dentro da classe BetStatusEnum. Um método fromString() por exemplo que recebe a string e retorna o betstatusenum

2024-10-28 19:48 UTC, uttoniWork commented on src/test/java/com/dape/api/usecase/service/BetServiceTest.java
> +        final Pageable pageable = PageRequest.of(0, 10);
A criação da Page acontece em todos os testes, crie um método privado para evitar o código duplicado

2024-10-28 19:48 UTC, uttoniWork commented on src/main/java/com/dape/api/domain/exception/GetBetsInvalidStatusException.java
> +public class GetBetsInvalidStatusException extends RuntimeException {
Esta excessão parece ser lançada para qualquer valor que não seja um status válido e nao apenas no fluxo de listagem necessariamente. Renomear para algo genérico como: InvalidBetStatusException

2024-10-28 19:48 UTC, uttoniWork commented on src/main/java/com/dape/api/adapter/repository/BetRepository.java
> +    @Query(
Essa query não atende o filtro opcional dos campos. Se buscarmos pelo status apenas e não informar data de criação ou update, ela vai retornar apenas bets com o status informado e com datas nulas ou iguais ao valor passado (também nulo). Dá uma espiada em  Querydsl pra criar predicados dinamicos: https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

Temos implementado algo do tipo em nossas apis, posso te mostrar também

2024-11-01 13:04 UTC, uttoniWork approved these changes

2024-11-01 20:15 UTC, lekramon approved these changes

2024-11-04 14:14 UTC, leandro-manoel approved these changes

2024-11-04 14:16 UTC, merged